name: build-windows-installer

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r "Sidour-avoda-Tzora-chevron/requirements.txt" pyinstaller

      - name: Build portable exe with PyInstaller
        shell: pwsh
        run: |
          cd "Sidour-avoda-Tzora-chevron"
          pyinstaller --noconsole --name "Sidour Avoda" --icon assets\calender-2389150_960_720.png --add-data "assets\calender-2389150_960_720.png;assets" --add-data "planning_data.db;." main.py

      - name: Upload portable build artifact
        uses: actions/upload-artifact@v4
        with:
          name: sidour-avoda-win-portable
          path: Sidour-avoda-Tzora-chevron/dist/**

      - name: Install Inno Setup
        run: choco install innosetup --yes

      - name: Build Windows installer (Inno Setup)
        shell: pwsh
        run: |
          & "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" "Sidour-avoda-Tzora-chevron\windows_installer.iss"

      - name: Upload installer artifact
        uses: actions/upload-artifact@v4
        with:
          name: sidour-avoda-setup
          path: Sidour-avoda-Tzora-chevron/dist_installer/**


